### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by marceltoepler** [Farfar/homeassistant-seatconnect#11]
I try to use seat connect but got following error during configuration:

```
home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [custom_components.seatconnect.config_flow] Creating connection to Seat Connect
home-assistant   | 2021-11-04 19:21:42 INFO (MainThread) [seatconnect.connection] Init Seat Connect library, version 1.1.3
home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [seatconnect.connection] Using service https://msg.volkswagen.de
home-assistant   | 2021-11-04 19:21:42 INFO (MainThread) [seatconnect.connection] Initiating new login
home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [seatconnect.connection] Starting authorization process for client seat
home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Got redirect to signin-service
home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Start authorization for user xxx@xxx.xx
home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Finalizing login
home-assistant   | 2021-11-04 19:21:44 DEBUG (MainThread) [seatconnect.connection] Received authorization code, exchange for tokens.
home-assistant   | 2021-11-04 19:26:44 ERROR (MainThread) [seatconnect.connection] Login failed for xxx@xxx.xx,

```

Because the 5 minutes delay between the last two log entries, I suspect a timeout gets exceedet.

Maybe someone else already had the same problem?

**Comment by Farfar** [comment]
> I try to use seat connect but got following error during configuration:
> 
> ```
> home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [custom_components.seatconnect.config_flow] Creating connection to Seat Connect
> home-assistant   | 2021-11-04 19:21:42 INFO (MainThread) [seatconnect.connection] Init Seat Connect library, version 1.1.3
> home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [seatconnect.connection] Using service https://msg.volkswagen.de
> home-assistant   | 2021-11-04 19:21:42 INFO (MainThread) [seatconnect.connection] Initiating new login
> home-assistant   | 2021-11-04 19:21:42 DEBUG (MainThread) [seatconnect.connection] Starting authorization process for client seat
> home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Got redirect to signin-service
> home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Start authorization for user xxx@xxx.xx
> home-assistant   | 2021-11-04 19:21:43 DEBUG (MainThread) [seatconnect.connection] Finalizing login
> home-assistant   | 2021-11-04 19:21:44 DEBUG (MainThread) [seatconnect.connection] Received authorization code, exchange for tokens.
> home-assistant   | 2021-11-04 19:26:44 ERROR (MainThread) [seatconnect.connection] Login failed for xxx@xxx.xx,
> ```
> 
> Because the 5 minutes delay between the last two log entries, I suspect a timeout gets exceedet.
> 
> Maybe someone else already had the same problem?

These kind of issues are API related and occur because the service isn't responding. Try again another day.
