### ISSUE TITLE
km to mi conversion incorrect

### ISSUE THREAD

**Issue by greghesp** [Farfar/homeassistant-seatconnect#12]
Looking on my Cupra Connect app, I can see that the odometer is currently at 3678km, and the next service is in 23400km

I've got the configuration set to km to mi, however the sensor for the odometer is reading 367.8 mil and the service is reading 2,639.3 mil, so the same thing.

The correct conversion if I change the units in the Cupra Connect app should be 2285miles on the odometer and service in 16400 miles

**Comment by Farfar** [comment]
> Looking on my Cupra Connect app, I can see that the odometer is currently at 3678km, and the next service is in 23400km
> 
> I've got the configuration set to km to mi, however the sensor for the odometer is reading 367.8 mil and the service is reading 2,639.3 mil, so the same thing.
> 
> The correct conversion if I change the units in the Cupra Connect app should be 2285miles on the odometer and service in 16400 miles

This is expected behaviour. If you want miles then switch to imperial units. The "mil" is not equal to "miles". You have chosen conversion from km to scandinavian "mil".
