### ISSUE TITLE
Unable to install package seatconnect / HA 2022.2.0b5

### ISSUE THREAD

**Issue by streilu** [Farfar/homeassistant-seatconnect#19]
The plugin (new version 1.1.4) doesn't work in HA 2022.2.0b5, here is the log:

`2022-02-01 12:47:43 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package seatconnect>=1.1.4: ERROR: Could not find a version that satisfies the requirement pytest_asyncio==1000000000.0.0 (from -c /usr/src/homeassistant/homeassistant/package_constraints.txt (line 88)) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.3.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0.dev0, 0.10.0, 0.11.0, 0.12.0, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.17.0a3, 0.17.0a4, 0.17.0a6, 0.17.0, 0.17.1, 0.17.2)
ERROR: No matching distribution found for pytest_asyncio==1000000000.0.0 (from -c /usr/src/homeassistant/homeassistant/package_constraints.txt (line 88))
WARNING: You are using pip version 20.2.4; however, version 22.0.2 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-02-01 12:47:43 ERROR (MainThread) [homeassistant.setup] Setup failed for seatconnect: Requirements for seatconnect not found: ['seatconnect>=1.1.4'].`

**Comment by SrOne** [comment]
Get same message with official 2022.2.0 version. 
:(

**Comment by streilu** [comment]
Works with last release, thank you!
