### ISSUE TITLE
Fetch vehicles failed with error: Token is invalid for client

### ISSUE THREAD

**Issue by rlesniak** [Farfar/homeassistant-seatconnect#20]
Hey. Thanks for your effort. I have an issue. I type valid email/password but in logs I see that error:
`Fetch vehicles failed with error: Token is invalid for client`.

Any ideas? I have one car Seat Leon

**Comment by doktormerlin** [comment]
I have the same issue, my car is a Cupra Formentor. Plugin Version 1.1.3


Logfiles show the following:

```
Logger: seatconnect.connection
Source: /usr/local/lib/python3.9/site-packages/seatconnect/connection.py:1513
First occurred: 10:17:45 PM (14 occurrences)
Last logged: 10:22:11 PM

Could not refresh tokens: 'seat'
```

```
Logger: seatconnect.connection
Source: /usr/local/lib/python3.9/site-packages/seatconnect/connection.py:316
First occurred: 10:17:43 PM (24 occurrences)
Last logged: 10:23:33 PM

Login failed for myaccount@email.com. The server might be temporarily unavailable, try again later. If the problem persists, verify your account at https://my.seat/portal/
```

However, logging in via the app (or on my.seat/portal) works fine

**Comment by doktormerlin** [comment]
I updated to HA 2022.2.0 and now I get the error mentioned in #19

**Comment by rlesniak** [comment]
After update to 1.1.4 I can login. Closing
