### ISSUE TITLE
Cupra Born

### ISSUE THREAD

**Issue by initdebugs** [Farfar/homeassistant-seatconnect#25]
Hi, I would like to try and use your repo with my Cupra Born, but that doesn't work. I think Cupra works slightly different. Could you help me with that  the Cupra Born is compatible with Home Assistant? Thanks!

**Comment by viking2010** [comment]
I've got a Cupra Born and would be interested too, but trying this integration doesn't work with my "My Cupra App" logon details.

**Comment by Tobazz** [comment]
Maybe check this : 
https://github.com/tillsteinbach/WeConnect-python/issues/26

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
