### ISSUE TITLE
Model image for Cupra Formentor 2.0

### ISSUE THREAD

**Issue by AcidAces** [Farfar/homeassistant-seatconnect#27]
Hi, model image for cupra formentor 2.0 is just a white silhouette of a car
![new-w1080](https://user-images.githubusercontent.com/110767220/188627313-99415da9-f172-4ead-94ec-563ddd15abc3.png)

**Comment by novus84** [comment]
How can I change this?

**Comment by SirMartin** [comment]
is there any option/advance for that?

**Comment by novus84** [comment]
download a picture and save it in HA, then create/edit your /config/customize.yaml

customize:
  device_tracker._**YOURCUPRA**_:
    friendly_name: **CUPRA**
    entity_picture: local/bilder/cupra.png


![image](https://github.com/Farfar/homeassistant-seatconnect/assets/57588422/f61bfdeb-a682-4f05-b5f1-e18f764df36b)

**Comment by SirMartin** [comment]
It works like a charm! Thanks

**Comment by ArnolddeBolster** [comment]
this solved it for me too

**Comment by Cornitus** [comment]
Hello, thanks for your work!

Is there perhaps a solution in sight here? @novus84 solution doesn't work for me. 

I have this in my configuration.yaml:

`homeassistant:
  customize:
    device_tracker.FIN_position:
      friendly_name: CUPRA
      entitity_picture: /local/images/CUPRA.png`

This is consistently ignored on the standard map and the white image continues to be displayed. Integrating customize.yaml via include produces the same result. Does anyone have another idea? Why can't you simply adjust this in the integration?

thank you for your time

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
