### ISSUE TITLE
Integration loses values

### ISSUE THREAD

**Issue by Schlichi83** [Farfar/homeassistant-seatconnect#36]
After a few hours I lose all values from SEAT Connect integration (all values „not available“). If you go to integrations and click on reload, it works again. But loses the values again after some time.

This is what the log says:
Logger: seatconnect.connection Source: custom_components/seatconnect/init.py:818 Integration: Seat Connect (documentation, issues) First occurred: 3. Juli 2023 um 21:37:55 (4707 occurrences) Last logged: 14:53:41
and
Logger: custom_components.seatconnect Source: custom_components/seatconnect/init.py:756 Integration: Seat Connect (documentation, issues) First occurred: 3. Juli 2023 um 21:37:56 (1569 occurrences) Last logged: 14:53:41
An error occured while requesting update from Seat Connect: 'serviceInfo'

I already set the poll interval to 10min and completely reinstalled the integration (even removed it from HACS). But the problem persists. What can I do?

**Comment by Schlichi83** [comment]
Am I really the only one with this problem?

This issue, reported with Skoda Connect, seems very similar to my issue:
https://github.com/skodaconnect/homeassistant-skodaconnect/issues/165

The entities become unavialable very unregularly. Sometimes it takes almost a whole day, sometimes it's every half hour. It seems like it happens more often, if something changes - e.g. vehicle is charging and changing its SoC or if you drive somewhere and have a new location and lower SoC afterwards.

**Comment by stevenise** [comment]
same here! 
HA Version 2023.07.1

**Comment by Schlichi83** [comment]
Finally ... it's not just me!

**Comment by javier-develop** [comment]
I have the same problem with seatconnect, and I lose connection after some time . 

I tried everything (uninstall, delete all  and reinstall) but the problem persist.

**Comment by Schlichi83** [comment]
Is there anything we can provide to get that fixed?

**Comment by dnnrwttr** [comment]
Also interested... Bought f***ing cupra connect for 69 bugs... and now that :(

**Comment by ronald-den-otter** [comment]
> After a few hours I lose all values from SEAT Connect integration (all values „not available“). If you go to integrations and click on reload, it works again. But loses the values again after some time.
> 
> This is what the log says: Logger: seatconnect.connection Source: custom_components/seatconnect/init.py:818 Integration: Seat Connect (documentation, issues) First occurred: 3. Juli 2023 um 21:37:55 (4707 occurrences) Last logged: 14:53:41 and Logger: custom_components.seatconnect Source: custom_components/seatconnect/init.py:756 Integration: Seat Connect (documentation, issues) First occurred: 3. Juli 2023 um 21:37:56 (1569 occurrences) Last logged: 14:53:41 An error occured while requesting update from Seat Connect: 'serviceInfo'
> 
> I already set the poll interval to 10min and completely reinstalled the integration (even removed it from HACS). But the problem persists. What can I do?

Sounds to me it loses connection after the token is expired. Then after reload it gets with login a new token.

**Comment by FuturamaPhill** [comment]
Same issue here

**Comment by javier-develop** [comment]
I have the same error since several weeks.

I think that the problem could be problems with the token. I have this log register.

"Logger: seatconnect.connection
Source: custom_components/seatconnect/__init__.py:818
Integration: Seat Connect ([documentation](https://github.com/farfar/homeassistant-seatconnect/blob/main/README.md), [issues](https://github.com/farfar/homeassistant-seatconnect/issues))
Could not refresh tokens: Token is invalid for client"

**Comment by JayReturns** [comment]
I have the same problem. It feels like Seat is restricting these automated API-Calls. If the integration looses it's values, my Cupra app also stops working and I cannot login anymore. I have to wait sometimes about two days until it works again. I fear that it's a problem might not be fixable.

**Comment by Schlichi83** [comment]
> I have the same problem. It feels like Seat is restricting these automated API-Calls. If the integration looses it's values, my Cupra app also stops working and I cannot login anymore. I have to wait sometimes about two days until it works again. I fear that it's a problem might not be fixable.

Strange ... since the last SEAT Connect update a few days ago, I don't have the problem anymore. The integration doesn't lose the values anymore. Did you all update to the newest version?

**Comment by JayReturns** [comment]
> Strange ... since the last SEAT Connect update a few days ago, I don't have the problem anymore. The integration doesn't lose the values anymore. Did you all update to the newest version?

Yes  I'm using Version 1.1.9 and I'm getting the following error mesages

` An error was encountered during interaction with the API: 'serviceInfo' `

`Received unhandled error indicating client-side problem. Restart or try again later.
Could not fetch operation list, HTTP status code: 429`
(Btw error 429 is "Too Many Requests")

` Error fetching seatconnect data: No vehicles found. `


I don't know where the error is exactly

**Comment by javier-develop** [comment]
I have 2 cars Mii and I have set the time to 30, 60, 120 and 300 and the result is the same for both of them. They dont connect from time to time, but not at the same time. There is no rules, aparently

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
