### ISSUE TITLE
SeatConnect: name 'atoken' is not defined

### ISSUE THREAD

**Issue by andig** [Farfar/homeassistant-seatconnect#39]
I was trying https://github.com/Farfar/seatconnect 1.1.8 directly; posting here since issues are not enabled. Fails with Leon Hybrid:

```
...
DEBUG:seatconnect.connection:User consent is valid, no missing information for profile
DEBUG:seatconnect.connection:Client "vwg" token is missing, call to authorize the client.
DEBUG:seatconnect.connection:Trying to fetch api tokens.
DEBUG:seatconnect.connection:Verifying token for ha-5a.prd.eu.vwg.vwautocloud.net
DEBUG:seatconnect.connection:VW-Group API token verified OK.
Traceback (most recent call last):
  File "/Users/andig/htdocs/seatconnect/seatconnect/connection.py", line 710, in get_vehicles
    exp = jwt.decode(atoken, options={'verify_signature': False}).get('sub', None)
                     ^^^^^^
NameError: name 'atoken' is not defined
```
Looking at the code it was not obvious for me where the `atoken` should come from.

**Comment by andig** [comment]
When patching the subject next step fails as well:

    raise SeatConfigException("No vehicles were found for given account!")

**Comment by yoku70** [comment]
Unfortunately, after upgrading to version 2023.09 of home assistant, the integration no longer works

**Comment by andig** [comment]
@Farfar also see https://github.com/evcc-io/evcc/pull/9703 for what had to be changed for evcc to retrieve list of vehicles.

**Comment by ahivert** [comment]
fixed with release 1.1.9

**Comment by RamBra** [comment]
Installed release 1.1.9 and all is well.
Thanks.

**Comment by yoku70** [comment]
thanks farfar, with the new version everything is working perfectly again
