### ISSUE TITLE
Pre-heater not working 

### ISSUE THREAD

**Issue by Atsharim** [Farfar/homeassistant-seatconnect#41]
Hello guys, thank you very much for the integration. It works for the most part, but regarding the winter, triggering the auxiliary heating system does not work. 
Home Assistant connects to the car, the status changes to "in progress" then "progress connected" and after some time, it shows "Request results Failed" and "progress disconnected"

**Comment by gforums** [comment]
+1 from me. 
Using the non-HA python script and the function "vehicle.set_pheater(mode = "heating", spin = "1234")".

It returns also "failed" for me.

Or do I need to trigger this as well before?

            print('#         Update preheater data        #')
            print(txt.center(40, '#'))
            await vehicle.get_preheater()
            print('')


My car is a Cupra formentor. Lock/Unlock works well!

thank you

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
