### ISSUE TITLE
No vehicles found - again

### ISSUE THREAD

**Issue by metcrl** [Farfar/homeassistant-seatconnect#42]
Hello guys,
Here we go again: it seems that we are here with the same problem. The Connect app for me it's working.
I hope that like the #37 someone can understand and fix the problem..

**Comment by scruz84** [comment]
Hi, I have a similar problem. 

The following error is shown on homeassistant.log file. It seems that the integration is sending too much requests.

`2023-10-09 19:30:25.062 WARNING (MainThread) [seatconnect.connection] Could not fetch operation list, HTTP status code: 429`

I had 60 as interval value. I am going to try with 600... tomorrow.
