### ISSUE TITLE
Failed to load Seat Connect icon

### ISSUE THREAD

**Issue by viper-sg2** [Farfar/homeassistant-seatconnect#43]
Failed to load custom brind icon:

<img slot="graphic" referrerpolicy="no-referrer" alt="Seat Connect" src="https://brands.home-assistant.io/seatconnect/icon.png">

the URL doesn't exist.
Maybe this?
https://github.com/home-assistant/brands/blob/master/custom_integrations/cupra_we_connect/icon.png

**Comment by ArnolddeBolster** [comment]
maybe this helps:
https://github.com/Farfar/homeassistant-seatconnect/issues/27#issuecomment-1733647901

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
