### ISSUE TITLE
Login failed, hassio and App

### ISSUE THREAD

**Issue by bartj12** [Farfar/homeassistant-seatconnect#45]
Goodmorning,

Since 1 week the connection fails randomly for both seat connect in HA as with the seat app.

The integration gives the error "failed to setup, will retry". After a couple of hours, without changing anything, it works again.

My HA issuelog is full with these errors:

2023-11-04 09:09:09.273 WARNING (MainThread) [seatconnect.connection] Unable to fetch authorization endpoint
2023-11-04 09:09:09.274 ERROR (MainThread) [seatconnect.connection] An API error was encountered during login, try again later
2023-11-04 09:10:40.908 WARNING (MainThread) [seatconnect.connection] Invalid credentials or invalid configuration. Make sure you have entered the correct credentials

Again, it looks like to resolve itself in time and reappears in time.

Any advice?

**Comment by jressel01** [comment]
VWGroup set a limit of 1000 Requests per day. Change Configuration and set the poll to 120(the field was seconds not minutes) and alls is fine. Then it ask every 2 minutes.
i Make a Pull request for it.

**Comment by bartj12** [comment]
Thanks, changed to 120 and will monitor the coming days

**Comment by jressel01** [comment]
you must wait until tomorow 1:00 in the morning you get data

**Comment by bartj12** [comment]
Works again, will monitor for the rest of the day and close the issue.

Thanks!

**Comment by jressel01** [comment]
i test it the last days. the minimum Value 90 works also because i get 960 requests per day. but with 120 i have more requests for other thinks.

**Comment by bartj12** [comment]
120 did the trick!
