### ISSUE TITLE
Failed to set token for "seat"

### ISSUE THREAD

**Issue by bartj12** [Farfar/homeassistant-seatconnect#47]
Goodmorning,

I have regularly these warnings in my log file:

WARNING (MainThread) [seatconnect.connection] Could not fetch realCarData, error: Failed to set token for "seat"

After a couple of days it looks like the server side blocks my connection (both HA as the Seat App), it comes back to live after some hours without changing anything at my side:

WARNING (MainThread) [seatconnect.connection] Could not fetch StoredVehicleDataResponse, error: 0
ERROR (MainThread) [seatconnect.connection] Received unhandled error indicating server-side problem.
WARNING (MainThread) [seatconnect.connection] Could not fetch pre-heating, HTTP status code: 504
WARNING (MainThread) [seatconnect.connection] Could not fetch trip statistics, error: 'NoneType' object has no attribute 'get'
etc...

I searched on the token issue, but could not find a solution yet.

Any advice?

p.s. is there a way to support / contribute to your project? (Paypal?)

**Comment by bartj12** [comment]
Please see below the complete issue information from the log in HA:

Logger: seatconnect.connection
Source: runner.py:188
First occurred: 10:01:56 AM (1 occurrences)
Last logged: 10:01:56 AM

Could not fetch realCarData, error: Failed to set token for "seat"

**Comment by renini** [comment]
Might be related: https://github.com/skodaconnect/homeassistant-skodaconnect/issues/235

**Comment by bartj12** [comment]
Thanks @renini
I do not think it is related. I have 300 seconds in my configuration.

**Comment by bartj12** [comment]
@Farfar, Any idea what is going on?

Thank you

**Comment by Farfar** [comment]
> @Farfar, Any idea what is going on?
> 
> Thank you

Sorry I have no idea. Without a proper trace its hard to pinpoint. But best guess is it has something to do with throttling.

**Comment by bartj12** [comment]
Hi, 

I have turned on debug mode, please see below the logfile around this topic. 

Hopefully it helps. 

2023-12-10 10:57:34.300 DEBUG (MainThread) [custom_components.seatconnect] Updating data from Seat Connect
2023-12-10 10:57:35.517 WARNING (MainThread) [seatconnect.connection] Could not fetch realCarData, error: Failed to set token for "seat"
2023-12-10 10:57:36.898 DEBUG (MainThread) [custom_components.seatconnect] Finished fetching seatconnect data in 2.597 seconds (success: True)

Edit: the WARNING above appears exactly every hour.

**Comment by Itamamuel** [comment]
Samething happens here... 10 min after i install the integrations.. everything becomes unavailable and i get the Failed to set token message on the log

**Comment by iaah05** [comment]
I also have this issue.

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
