### ISSUE TITLE
Help Needed - Seat Connect and HomeAssistant Login Issues

### ISSUE THREAD

**Issue by Rasmuswoller** [Farfar/homeassistant-seatconnect#48]
Hey everyone,

I've been wrestling with Seat Connect login problems for a few months now, and I'm hoping someone here might have some insights or solutions.

Between 1 am and 11 am, everything's smooth – I can log in via the app, and HomeAssistant is doing its thing. But after 11 am, no dice. Can't log in through the app, and HomeAssistant isn't fetching any data.

I reached out to the Seat team, and after some back-and-forth, they suggested checking for third-party apps connected to Seat Connect. Lo and behold, after disconnecting HomeAssistant, the login problem vanished.

This setup was golden for two years, and suddenly, it's on the fritz. Did Seat tweak something recently, like putting a cap on data, or was there an update to the app?

I really want to get this system back up and running. I love having all my data in HomeAssistant.

Any ideas or help would be awesome.

Cheers,
Rasmus

**Comment by Schlichi83** [comment]
Hi Rasmus,
I have the same problem. I honestly thought in my case the issue was that three different apps connect to SEAT Connect:
- Home Assistant
- EVCC
- Tronity

So I removed the Home Assistant Plugin and now integrated the Tronity and EVCC data in Home Assistant. However, this is not nearly as good as having the data directly. For example you can't activate climate from HA anymore. And the SoC isn't updated as regularly as before.

So if there were a fix, I would happily go back to the SEAT Connect plugin.

Greets
Schlichi83

**Comment by bartj12** [comment]
Hi Rasmus,

My feeling is that seat recently changed something on the server side, I have no proof of this.

With some trial and error I noticed that changing the refresh interval to 600 seconds did the trick. 

I have still regular warnings in my log (issue 	47) and recently the error below has been showing. 
But I'm able to turn on the heating by automation and that's what's matter to me. 

_Logger: seatconnect.connection
Source: runner.py:188
First occurred: 1:56:18 AM (5 occurrences)
Last logged: 2:36:53 AM

Received unhandled error indicating server-side problem. The service might be temporarily unavailable._

**Comment by Rasmuswoller** [comment]
Hi Bartj12.
It looks like it worked for me changing the refresh interval to 600 second. 
Seat proberly changed an uppper limmit to how much we can refresh. 
But why did they not tell me that when trobleshooting.
Thanks for the advice !

**Comment by xXValiXx** [comment]
But the documentation says interval in minutes. Does this mean you set it to 600 minutes?
In the UI I used 60. But now I got the same problem.

**Comment by bartj12** [comment]
No, it is seconds.
There is a pull request to change this.

**Comment by Schlichi83** [comment]
> No, it is seconds. There is a pull request to change this.

I don't think it's seconds. I set to to 600 as well and my SoC is only updated every few hours. 600 minutes would be 10 hrs.

**Comment by herbod-nl** [comment]
I have been in contact with Seat because my Seat App was not working. They did some checking and noticed I was logging in with a 3rd party app (home assistant). I removed the app in Home assistant and my seat app on the phone was working without any problems.  Logging in in the seat app in home assistant just once a hour (or less) could solve the issue..

**Comment by ts8789** [comment]
I am facing same issue and can confirm support knows I am using 3rd party app. About 1 day after deactivating this component, App will work again. Not long after reactivating, my account and therefore receiving data is blocked again.

Oh guys, this pull request answers it all:
https://github.com/Farfar/homeassistant-seatconnect/pull/44

It's indeed seconds with wrong translation saying minutes, and with 60 seconds interval, you are exceeding 1000 requests limit! So setting to 90, you have 40 requests left...

**Comment by Rasmuswoller** [comment]
@ts8789, I don't think Seat can detect that you are using a third-party app, but I believe they have set a limit on how frequently you can request data from their system.

When using their app, you open it to retrieve data, perform your actions, exchange some data, and then close the app. On the other hand, HomeAssistant queries Seat for a status update every minute.

I noticed that my connection to Seat Connect was consistently lost around 11 am. I suspect that I exceeded the allowed number of requests for the day. To address this, I adjusted the HomeAssistant app to refresh every 5 minutes, and it seems to be working fine now.

I hope this information is helpful for you.

**Comment by jressel01** [comment]
Hi 
as i wrote in my pull request there is a limit of 1000 requests per day(All VAG Brands). now everyone can decide how many he wants to save for the SeatApp. If the number is reached, it will no longer work.
I have taken 100 sec for Home Assistant and no problems.

**Comment by ziki77** [comment]
Hi,
I put 120s and still had problem yesterday, does the number of total connections be influenced by the number of data (entities in HA) you want to get/display on HA? I mean, if I show 4 entities, every time the plug-in pools for them it makes one connection or 4 connections?
Thanks

**Comment by jressel01** [comment]
no. one request for all entities. but if you change it yesterday wait 1 day.

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
