### ISSUE TITLE
After Update to Core 2024.1.0

### ISSUE THREAD

**Issue by jressel01** [Farfar/homeassistant-seatconnect#49]
WARNING (MainThread) [homeassistant.components.device_tracker] SOURCE_TYPE_GPS was used from seatconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/farfar/homeassistant-seatconnect/issues

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
