### ISSUE TITLE
Cupra formentor

### ISSUE THREAD

**Issue by duchu** [Farfar/homeassistant-seatconnect#52]
Will this repo work with Formentor? I already installed it but I'm stuck on login screen.

**Comment by c0rrre** [comment]
Hi, 
I got a formentor and for me it is working.
Remember to change the update interval to 600

**Comment by duchu** [comment]
Okey, right now i have problem with login. When i enter creditentials from app circle is spinning and nothing happens. Then in hass log there is too much login attempts.

**Comment by sp7dpt** [comment]
> Hi, I got a formentor and for me it is working. Remember to change the update interval to 600

Why we must change update interval to 600, default is 60?

**Comment by c0rrre** [comment]
> > Hi, I got a formentor and for me it is working. Remember to change the update interval to 600
> 
> Why we must change update interval to 600, default is 60?

Because the VWGROUP limit requests to 1000 per day. With the default of 60 you will exceed this Limit and the values wont get updated any more

**Comment by sp7dpt** [comment]
ok, thanks for info

**Comment by sp7dpt** [comment]
Model image url of cupra formentor is white. Can I change it or can it be fixed?

![image](https://github.com/Farfar/homeassistant-seatconnect/assets/54576080/c2f1c0a5-4bd6-442c-a7bf-52dc3ae2effc)

**Comment by PokoLoko2014** [comment]
Where is this setting?

**Comment by MantovaniMatteo** [comment]
> > > Hi, I got a formentor and for me it is working. Remember to change the update interval to 600
> > 
> > 
> > Why we must change update interval to 600, default is 60?
> 
> Because the VWGROUP limit requests to 1000 per day. With the default of 60 you will exceed this Limit and the values wont get updated any more

aaaaaa ok, now i know the reason why it stops working after few hours! Thank you

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
