### ISSUE TITLE
Locking / Unlocking Cupra no longer working?

### ISSUE THREAD

**Issue by gforums** [Farfar/homeassistant-seatconnect#58]
Dear all, 
I used the python only script since a while to lock and unlock my cupra formentor.

Since around a week or two, it stopped working. 

This is part of the log when running the python script: 

DEBUG:seatconnect.connection:Request for “https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rlu/v1/seat/ES/vehicles/Vxxxxxxxx/requests/1913504598/status” returned with status code [200]

Is the issue known to you? 
The official app is working. Also updating some information like window states seem still to work...

Thanks a lot, 
Best, 
Christian

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
