### ISSUE TITLE
All entities unknown | development still active?

### ISSUE THREAD

**Issue by z-master42** [Farfar/homeassistant-seatconnect#59]
With regard to the Fork source (API changes), is this integration being developed further? Currently, all entities are unknown to me in Home Assistant or are no longer provided by the integration.

Get errors like this for all entity types used:

```
Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:356
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 5. Juni 2024 um 16:19:28 (2 Vorkommnisse)
Zuletzt protokolliert: 05:56:32

Error while setting up seatconnect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/seatconnect/sensor.py", line 22, in async_setup_entry
    data = hass.data[DOMAIN][entry.entry_id][DATA]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'xxx.....'
```

and also:

```
Logger: seatconnect.connection
Quelle: runner.py:190
Erstmals aufgetreten: 3. Juni 2024 um 20:51:01 (1548 Vorkommnisse)
Zuletzt protokolliert: 05:01:16

Could not fetch StoredVehicleDataResponse, error: 0
Could not fetch position, HTTP status code: 429
Could not fetch trip statistics, HTTP status code: 429
Could not fetch realCarData, error: Failed to set token for "seat"
Received unhandled error indicating client-side problem. Restart or try again later.
```

**Comment by kamil-bednarek** [comment]
same here

**Comment by z-master42** [comment]
Log out of the Seat Connect and/or MySeat app. When you log in again, new terms and conditions/data protection provisions will appear for you to approve, after which the integration should work again.

**Comment by oywino** [comment]
Didn't work. Never asked for no T's & C's
Still don't work.

**Comment by oywino** [comment]
Bump!
Any advise, please?
I'm on HAOS 2024.8.3
SEAT CONNECT Integration  1.1.9

Here's one of several errors logged:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:364
integration: Sensor (documentation, issues)
First occurred: 02:00:38 (2 occurrences)
Last logged: 23:25:06

Error while setting up seatconnect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/seatconnect/sensor.py", line 22, in async_setup_entry
    data = hass.data[DOMAIN][entry.entry_id][DATA]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01J57SZE642AK9EXXKHB176PTM'
```

**Comment by federicotravaini** [comment]
I'm facing the same issue and I can't solve it.

**Comment by oywino** [comment]
.... and today, suddenly, everything reappeared again, as if nothing had happened  (!)

**Comment by Farfar** [comment]
> .... and today, suddenly, everything reappeared again, as if nothing had happened (!)

API isn't rock solid. Sometimes VAG servers have incorrect/missing data and it might take a day or two until everything is working again.

This code is no longer being maintained by me and requires contributors in order to fix issues.

**Comment by oywino** [comment]
> This code is no longer being maintained by me and requires contributors in order to fix issues.
>
That's very sad news! 😶
Any particular reason why you will no longer maintain the code? We have become pretty much dependent on this integration.
Is there anything we can do to encourage further support from you?
I am regretfully no programmer myself.....

**Comment by z-master42** [comment]
As he explains in the readme:
> THIS IS NOT MAINTAINED SINCE I DON'T OWN A SEAT/CUPRA CAR
> If you can/want to take over development please send me a message

**Comment by oywino** [comment]
Oh, I didn't see that.
Maybe if we buy him one, and split the cost between us? 😂
(I'm afraid there's no lineup of people eager to take over maintenance, or ..... )

I think this illustrates one critical issue with the "Open Home Foundation" Home Assistant platform; More and more integrations grow stale over time as the original maintainer either lost interest, died or got married.
