### ISSUE TITLE
async_show_progress without passing a progress task is not valid and will break in Home Assistant Core 2024.8

### ISSUE THREAD

**Issue by Recte** [Farfar/homeassistant-seatconnect#62]
It shows that the project didn't had maintenance updates for a couple years. I hope you are still maintaining itsince the System log of Home Assistant writes:
```
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:819 
First occurred: 21:29:48 (2 occurrences) 
Last logged: 21:49:57

custom_components.seatconnect.config_flow::SeatConnectConfigFlow calls async_show_progress without passing a progress task,
this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
```
Through this issue I report this to you. Please take care and prevent the integration from breaking.

I noticed this log line because I am experiencing the issue that was reported onder https://github.com/Farfar/homeassistant-seatconnect/issues/60

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
I believe this is fixed in latest release thanks to a PR.
