### ISSUE TITLE
Login failed, the terms and conditions might have been updated

### ISSUE THREAD

**Issue by M4RCCR4FT** [Farfar/homeassistant-seatconnect#63]
After restarting HA today, this integration logs this:

```
Logger: seatconnect.connection
Bron: custom_components/seatconnect/__init__.py:796
integratie: Seat Connect ([documentatie](https://github.com/farfar/homeassistant-seatconnect/blob/main/README.md), [problemen](https://github.com/farfar/homeassistant-seatconnect/issues))
Eerst voorgekomen: 19:55:31 (11 gebeurtenissen)
Laatst gelogd: 20:05:10

Login failed, the terms and conditions might have been updated and need to be accepted. Login to https://my.seat/portal/ and accept the new terms before trying again
```
On the proposed website is stated:
```
Update notification
As of April 22nd 2022, the SEAT CONNECT portal is no longer available online. 
```
Is it possible to make this integration working again?

**Comment by mookkari** [comment]
The same issue happened to me yesterday. I logged into  https://seatid.vwgroup.io with my credentials and accepted all questions. Went back to HA and everything seems to work as expected.

**Comment by christianschneider89** [comment]
Can confirm this!

**Comment by M4RCCR4FT** [comment]
Confirmed aswell, thank you for your replies! Closed.

**Comment by Recte** [comment]
> The same issue happened to me yesterday. I logged into https://seatid.vwgroup.io with my credentials and accepted all questions. Went back to HA and everything seems to work as expected.

I logged on to the https://seatid.vwgroup.io/ and did the walk-through. When that didn't change the outcome, I went to https://cupraid.vwgroup.io/ and did the same (with the same account).

Since it’s al marketing / commercial consent, I don’t think it matters whether you give consent or not, but does anyone know their given consent to specific parts?

**Comment by M4RCCR4FT** [comment]
I gave all, after reading them, but only on seatid.vwgroup.io, while getting data from a Cupra Leon Sportstourer.
I also restarted HA, just to be sure, and after that the integration was happy again.

**Comment by Recte** [comment]
I think it's a different issue than [mine ](https://github.com/Farfar/homeassistant-seatconnect/issues/60#issuecomment-2198483640) you solved by doing that.
Just have permissions, bit it still failed.
The main errors (in the other issue ticket):
`Invalid credentials or invalid configuration. Make sure you have entered the correct credentials`
`Login failed with error: User appears unauthorized`

Even though the credentials are correct and the plus service is bought.

**Comment by M4RCCR4FT** [comment]
Did you also fill in your s-pin in the configuration of HA?

**Comment by trusky7** [comment]
I don't have s-pin activated but until a few days ago everything worked perfectly. Where is the s-pin activated in the app?

**Comment by trusky7** [comment]
I have configured S-pin and restarted HA but same thing. In another test HA, I have done integration again and logically until you log in with User and Psw doesn't let you put the S-pin so I can't configure it either.

**Comment by M4RCCR4FT** [comment]
Hmmm... Then I'm affraid I can't help you any further...

**Comment by Recte** [comment]
> Did you also fill in your s-pin in the configuration of HA?

No, I do not cause I don’t know how. After I select the integration, I get the following setup screen. 
<img width="375" alt="image" src="https://github.com/Farfar/homeassistant-seatconnect/assets/26491601/8ec31d59-1bb1-4461-b908-de61ee410fef">

The [integration options](https://github.com/farfar/homeassistant-seatconnect/blob/main/README.md#configuration-options) can be changed after setup by clicking on the "CONFIGURE" text on the integration.

But I can’t get passed the setup.

**Comment by M4RCCR4FT** [comment]
You are right, it's in the Options for Seat Connect screen, as you wrote. Just curious what brand and model car are you trying to connect?

**Comment by trusky7** [comment]
> You are right, it's in the Options for Seat Connect screen, as you wrote. Just curious what brand and model car are you trying to connect?

In my case Cupra León ST

**Comment by trusky7** [comment]
I have created a new user in My Cupra, accepted the terms and tried to add it in HA, but exactly the same thing happens. In the HA Log it says that you have to accept the terms, but I already have them accepted in both my user and the one I just created.

**Comment by dacorde** [comment]
After gerting crazy for days (accessing anywhere you mentioned to accept anything...), have found a solution could help.
I logged in with Tor Browser (any otehr browser with incognito mode may work). I have changed my region to Germany (I am actually in Spain). New terms have appeared so I have accepted them. Then it has worked in HA!!!!

**Comment by trusky7** [comment]
> After gerting crazy for days (accessing anywhere you mentioned to accept anything...), have found a solution could help. I logged in with Tor Browser (any otehr browser with incognito mode may work). I have changed my region to Germany (I am actually in Spain). New terms have appeared so I have accepted them. Then it has worked in HA!!!!

Luego volviste a Español? Yo me estoy volviendo loco también. Cuando me contestes lo pruebo. Gracias!!

**Comment by M4RCCR4FT** [comment]
@trusky7 thats weird, I also connect to a Cupra Leon ST! I'm in the Netherlands, and saw the above suggestion to swap region... Maybe give it a try?

**Comment by dacorde** [comment]
To do the above with other region, I created a new user yesterday (it looks to take a day to be validated), with an invite fron main user. Region is Germany but I keep Spanish language.
When accessing through official app it remains in Spanish.

Prueba a cambiar la región! No te influirá en nada! No me atrevo a poner España como region de nuevo... Jeje

**Comment by trusky7** [comment]
I have entered Seat Id, I have changed the region to Germany, it has made
me accept conditions, I have exited and entered again, it has made me
accept more conditions and then I have gone to HA but it tells me the same
thing.  I have done this with the user that I created this morning to
test.  Should I wait or something?

**Comment by trusky7** [comment]
Wow now yes!!! In my principal user wotks fine. Thxx

**Comment by pedestre** [comment]
I can confrm the solution... change region in the user website to germany (https://seatid.vwgroup.io/), log out, log in again, agree the terms and conditions (German version) and custom api working again. Thanks¡¡

**Comment by egarijo** [comment]
Me pasaba lo mismo. No podía logearme.  He cambiado la región, aceptado todas las condiciones, reiniciado la aplicación y ahora funciona.

**Comment by egarijo** [comment]
Después de estar funcionando durante muchos meses, ayer me dí cuenta que no estaba leyendo los datos del coche. Parece ser que alguna actualización de HA no le ha gustado y pide logearse de nuevo. Sin embargo me logeo y me sale nuevamente el aviso de aceptar todos los terminos. He ido a la cuenta, que porcierto estaba configurada la region como Germany, la he pasado a Spain, he aceptado todos los terminos. Después he de cerrar sesión he vuelto a abrir sesión desde otro navegador por si acaso, y he vuelto a cambiar de nuevo el la region a Germany. De nuevo he vuelto a aceptar todo y he cerrado sesión. Pero desde HA sigue sin poder iniciar sesión. ¿A alguno de los que le ha estado funcionando antes le ha ocurrido lo mismo en estos días?

**Comment by parasito** [comment]
I have same issue here. My account is in Germany account but I get an authentication error from HA.
