### ISSUE TITLE
async_forward_entry_setup stops working in HA 2025.01

### ISSUE THREAD

**Issue by z-master42** [Farfar/homeassistant-seatconnect#64]
Home Assistant Log Warning:

Detected code that calls async_forward_entry_setup for integration seatconnect with title: xxxxxxx and entry_id: yyyyyy, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by kamil-bednarek** [comment]
same here

**Comment by Didi-321** [comment]
got this warning to, plus two other ones:

Detected that custom integration 'seatconnect' calls async_forward_entry_setup for integration, seatconnect with title: XXXX and entry_id: YYYY, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/seatconnect/__init__.py, line 238: hass.async_create_task(, please create a bug report at https://github.com/farfar/homeassistant-seatconnect/issues

SOURCE_TYPE_GPS was used from seatconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please report it to the author of the 'seatconnect' custom integration

The last one will be easy to fix, I think, even with my knowledge in Python and HA Integrations. But the first two seem more complicated.

Edit: Saw this on another integration with the same error. Is the fix really so easy? And will it fix both issues?
![Screenshot_20241006_100539_Samsung Internet](https://github.com/user-attachments/assets/99fe81fd-8928-4eb0-bc0e-5629c1a1690f)

Edit2: Just saw, that there is already a Pull Request #50 for the GPS issue

**Comment by z-master42** [comment]
Looks like `hass.config_entries.async_forward_entry_setups(entry, [component])` is doing its job.
The integration works and no errors in the log.

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
I merged the PR in latest release and it will hopefully buy you some time!
Thanks @z-master42
