### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by aboogerd** [Farfar/homeassistant-seatconnect#68]
Hi, noticed the development is stopped a year ago.

In my situation the integration stopped working. Are you planning to have it updated? Or is this project dead?

Cheers Alexander

**Comment by tofferlicious** [comment]
For me it was necessary again to login into https://seatid.vwgroup.io/account and accept or decline their consent-requests. After that it worked. Would be nice though, if this could be handled by the extension somehow

**Comment by Farfar** [comment]
This code is no longer being maintained by me and requires contributors in order to fix issues.
