### ISSUE TITLE
Parking heater can be turned OFF but not ON from HA.

### ISSUE THREAD

**Issue by lassikos** [Farfar/homeassistant-seatconnect#9]
Hi. Thanks for the nice integration. All data is coming from the servers nicely, but maybe the most important feature; turn on parking heater does not work. If i turn parking heater on with android app e.g., and wait a while, it shows ON also in HA, from where it can be turned off. But turning it ON from HA doesn't do nothing. Switch stays on a while but then goes off position automatically. And nothing happens even waiting more than 10 minutes.

Nothing is reported to a logs either when trying to turn ON.

**Comment by Farfar** [comment]
Might be something from Skoda port that's not working correctly. Will have a look when I have the time.

**Comment by Farfar** [comment]
@lassikos I cannot reproduce this issue as I don't own a Seat and haven't got access to an account with a car that's got aux heater.
I will need full debug logs to be able to find out why this fails.
